import Header from '@/components/Header/Header';
import type { Metadata } from 'next';
import { myFontPanagram } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="apple-touch-icon" href="/logo.png"></link>
      <link rel="manifest" href="/manifest.json"></link>
      <body className={myFontPanagram.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
